const getSkillsForType = (type) => {
  const skills = {
    NormalTypeSkills: [
      {
        name: "あばれる（全体）",
        category: "Attack",
        power: 70,
        effect: null,
        successRate: null,
        isAoe: true,
      },
      {
        name: "しんそく",
        category: "Attack",
        power: 120,
        effect: null,
        successRate: null,
      },
      {
        name: "きあい",
        category: "Recovery",
        power: 120,
        effect: null,
        successRate: null,
      },
      {
        name: "ひみつのちから",
        category: "Special",
        power: 160,
        effect: "attack",
        successRate: 80,
      },
    ],
    FighitingTypeSkills: [
      {
        name: "ばくれつパンチ（全体）",
        category: "Attack",
        power: 80,
        effect: null,
        successRate: null,
        isAoe: true,
      },
      {
        name: "いのちがけ（全体）",
        category: "Special",
        power: 140,
        effect: null,
        successRate: 50,
        isAoe: true,
      },
      {
        name: "ボディプレス",
        category: "Attack",
        power: 120,
        effect: null,
        successRate: null,
      },
      {
        name: "はどうだん",
        category: "Special",
        power: 180,
        effect: "attack",
        successRate: 80,
      },
    ],
    FlyingTypeSkills: [
      {
        name: "アクロバット",
        category: "Attack",
        power: 110,
        effect: null,
        successRate: null,
      },
      {
        name: "おいかぜ（全体）",
        category: "Recovery",
        power: 60,
        effect: null,
        successRate: null,
        isAoe: true,
      },
      {
        name: "そらをとぶ",
        category: "Defence",
        power: null,
        effect: null,
        successRate: null,
      },
      {
        name: "ぼうふう",
        category: "Special",
        power: null,
        effect: "confuse",
        successRate: 90,
      },
    ],    
    PoisonTypeSkills: [
      {
        name: "アシッドボム",
        category: "Attack",
        power: 100,
        effect: null,
        successRate: null,
      },
      {
        name: "スモッグ（全体）",
        category: "Special",
        power: null,
        effect: "sleep",
        successRate: 70,
        isAoe: true,
      },
      {
        name: "どくばり",
        category: "Attack",
        power: 120,
        effect: null,
        successRate: null,
      },
      {
        name: "ようかいえき（全体）",
        category: "Special",
        power: 80,
        effect: "attack",
        successRate: 60,
        isAoe: true,
      },
    ],    
    GroundTypeSkills: [
      {
        name: "マグニチュード（全体）",
        category: "Special",
        power: 140,
        effect: null,
        successRate: 40,
        isAoe: true,
      },
      {
        name: "あなをほる",
        category: "Defence",
        power: null,
        effect: null,
        successRate: null,
      },
      {
        name: "どろあそび",
        category: "Recovery",
        power: 80,
        effect: null,
        successRate: null,
      },
      {
        name: "グランドフォース（全体）",
        category: "Special",
        power: 150,
        effect: "recovery",
        successRate: 60,
        isAoe: true,
      },
    ],    
    RockTypeSkills: [
      {
        name: "いわなだれ",
        category: "Attack",
        power: 100,
        effect: null,
        successRate: null,
      },
      {
        name: "メテオビーム（全体）",
        category: "Special",
        power: 110,
        effect: "attack",
        successRate: 50,
        isAoe: true,
      },
      {
        name: "げんしのちから",
        category: "Recovery",
        power: 120,
        effect: null,
        successRate: null,
      },
      {
        name: "ロックカット",
        category: "Defence",
        power: null,
        effect: null,
        successRate: null,
      },
    ],    
    BugTypeSkills: [
      {
        name: "まとわりつく（全体）",
        category: "Special",
        power: null,
        effect: "confuse",
        successRate: 80,
        isAoe: true,
      },
      {
        name: "とどめばり",
        category: "Special",
        power: 190,
        effect: "attack",
        successRate: 80,
        
      },
      {
        name: "きゅうけつ",
        category: "Recovery",
        power: 120,
        effect: null,
        successRate: null,
      },
      {
        name: "むしのていこう",
        category: "Special",
        power: 140,
        effect: "recovery",
        successRate: 90,
      },
    ],    
    GhostTypeSkills: [
      {
        name: "かげうち",
        category: "Attack",
        power: 120,
        effect: null,
        successRate: null,
      },
      {
        name: "シャドーボール（全体）",
        category: "Special",
        power: 90,
        effect: "attack",
        successRate: 40,
        isAoe: true,
      },
      {
        name: "ひゃっきやこう",
        category: "Recovery",
        power: 120,
        effect: null,
        successRate: null,
      },
      {
        name: "おどろかす",
        category: "Special",
        power: null,
        effect: "confuse",
        successRate: 90,
      },
    ],    
    SteelTypeSkills: [
      {
        name: "アイアンヘッド",
        category: "Attack",
        power: 110,
        effect: null,
        successRate: null,
      },
      {
        name: "てっぺき",
        category: "Defence",
        power: null,
        effect: null,
        successRate: null,
      },
      {
        name: "はめつのねがい（全体）",
        category: "Special",
        power: null,
        effect: "sleep",
        successRate: 70,
        isAoe: true,
      },
      {
        name: "バレットパンチ",
        category: "Special",
        power: 170,
        effect: "attack",
        successRate: 80,
      },
    ],    
    FireTypeSkills: [
      {
        name: "かえんほうしゃ（全体）",
        category: "Attack",
        power: 80,
        effect: null,
        successRate: null,
        isAoe: true,
      },
      {
        name: "かえんのまもり",
        category: "Defence",
        power: null,
        effect: null,
        successRate: null,
      },
      {
        name: "おにび",
        category: "Recovery",
        power: 120,
        effect: null,
        successRate: null,
      },
      {
        name: "やけっぱち",
        category: "Special",
        power: 180,
        effect: "attack",
        successRate: 70,
      },
    ],    
    WaterTypeSkills: [
      {
        name: "ハイドロポンプ（全体）",
        category: "Attack",
        power: 70,
        effect: null,
        successRate: null,
        isAoe: true,
      },
      {
        name: "なみのり",
        category: "Defence",
        power: null,
        effect: null,
        successRate: null,
      },
      {
        name: "みずあそび",
        category: "Recovery",
        power: 140,
        effect: null,
        successRate: null,
      },
      {
        name: "ひやみず",
        category: "Special",
        power: null,
        effect: "confuse",
        successRate: 90,
      },
    ],
    GrassTypeSkills: [
      {
        name: "タネマシンガン",
        category: "Attack",
        power: 130,
        effect: null,
        successRate: null,
      },
      {
        name: "なやみのたね",
        category: "Special",
        power: null,
        effect: "confuse",
        successRate: 90,
      },
      {
        name: "こうごうせい",
        category: "Recovery",
        power: 110,
        effect: null,
        successRate: null,
      },
      {
        name: "このは（全体）",
        category: "Special",
        power: null,
        effect: "sleep",
        successRate: 80,
        isAoe: true,
      },
    ],
    ElectricTypeSkills: [
      {
        name: "らいげき",
        category: "Attack",
        power: 120,
        effect: null,
        successRate: null,
      },
      {
        name: "10まんボルド（全体）",
        category: "Special",
        power: 100,
        effect: "attack",
        successRate: 60,
        isAoe: true,
      },
      {
        name: "じゅうでん",
        category: "Recovery",
        power: 140,
        effect: null,
        successRate: null,
      },
      {
        name: "でんきショック",
        category: "Special",
        power: null,
        effect: "sleep",
        successRate: 90,
      },
    ],
    PsychicTypeSkills: [
      {
        name: "ひかりのかべ（全体）",
        category: "Recovery",
        power: 100,
        effect: null,
        successRate: null,
        isAoe: true,
      },
      {
        name: "サイコキネシス",
        category: "Special",
        power: null,
        effect: "confuse",
        successRate: 90,
      },
      {
        name: "ゆめくい",
        category: "Attack",
        power: 120,
        effect: null,
        successRate: null,
      },
      {
        name: "めいそう",
        category: "Recovery",
        power: 110,
        effect: null,
        successRate: null,
      },
    ],
    IceTypeSkills: [
      {
        name: "れいとうビーム",
        category: "Attack",
        power: 120,
        effect: null,
        successRate: null,
      },
      {
        name: "こごえるかぜ（全体）",
        category: "Special",
        power: null,
        effect: "sleep",
        successRate: 70,
        isAoe: true,
      },
      {
        name: "オーロラベール",
        category: "Defence",
        power: null,
        effect: null,
        successRate: null,
      },
      {
        name: "ぜったいれいど",
        category: "Special",
        power: 9999,
        effect: "attack",
        successRate: 60,
      },
    ],
    DragonTypeSkills: [
      {
        name: "ドラゴンクロー",
        category: "Attack",
        power: 120,
        effect: null,
        successRate: null,
      },
      {
        name: "りゅうのまい",
        category: "Special",
        power: 150,
        effect: "recovery",
        successRate: 70,
      },
      {
        name: "りゅうせいぐん（全体）",
        category: "Special",
        power: 140,
        effect: "attack",
        successRate: 40,
        isAoe: true,
      },
      {
        name: "あくうせつだん",
        category: "Special",
        power: null,
        effect: "confuse",
        successRate: 90,
      },
    ],
    DarkTypeSkills: [
      {
        name: "だましうち",
        category: "Attack",
        power: 100,
        effect: null,
        successRate: null,
      },
      {
        name: "うそなき（全体）",
        category: "Special",
        power: null,
        effect: "confuse",
        successRate: 70,
        isAoe: true,
      },
      {
        name: "ちょうはつ",
        category: "Defence",
        power: null,
        effect: null,
        successRate: null,
      },
      {
        name: "ダークホール",
        category: "Special",
        power: null,
        effect: "sleep",
        successRate: 90,
      },
    ],
    defaultSkills: [
      {
        name: "たたかう",
        category: "Attack",
        power: 70,
        effect: null,
        successRate: null,
      },
      {
        name: "まもる",
        category: "Defence",
        power: null,
        effect: null,
        successRate: null,
      },
      {
        name: "かいふく",
        category: "Recovery",
        power: 50,
        effect: null,
        successRate: null,
      },
      {
        name: "すいみん",
        category: "Special",
        power: 90,
        effect: "sleep",
        successRate: 80,
      },
    ],
  };

  // タイプの最初の文字を大文字に変換し、残りはそのままにしてキー名を生成
  const skillType = type.charAt(0).toUpperCase() + type.slice(1);
  const skillKey = `${skillType}TypeSkills`;
  console.log(skillKey);
  return skills[skillKey] || skills['defaultSkills'];
};

export { getSkillsForType };
